### ISSUE TITLE
Terminology in Appendix: Punctuation

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#21]
I think the appendix could be made clearer by using more conventional terminology in some cases. My biggest beef is with 'message expression'. Wouldn't this be clearer to most people as 'method call'? 

For greatest clarity, it would be nice if you gave the actual character in each case as well as the name and unicode codepoint. So, the title for each paragraph could be something like:

   Ampersand (U+0026) &

Aside from that, you've adopted unicodish names for the characters. In many cases that's fine, but some of the names unicode uses are rather obscure. How many people really call ^ a 'circumflex accent', or . a 'full stop'. (What, is this the telegraph office?) Since in every case you also list the unicode codepoint in U+NNNN form, it should be perfectly clear which character you're talking about. 

I suggest the following changes in character names:

Circumflex Accent => caret
Commercial At Sign => at sign
Full Stop => dot
Grave Accent => backtick
Hyphen Minus Sign => dash
Low Line => underscore
Reverse Solidus => backslash
Solidus => slash

**Comment by runpaint** [comment]
> My biggest beef is with 'message expression'. Wouldn't this be
> clearer to most people as 'method call'?

I suspected this would raise eyebrows. :-) I'm not set on it, but let me justify my decision. For pedagogical reasons I separated messages from methods. This allows the former to be introduced as requests for an object to perform an operation, and the latter as the means with which an object performs an operation. Not only is this in keeping with the SmallTalk heritage, and more consistent with our use of the term 'receiver', but it also addresses Ruby's dynamism. A 'method call' or 'function call' typically has an unambiguous mapping to a corresponding method or function. We define a method called m, then call it with m(). Ruby, of course, doesn't behave this way.A selector may correspond with a method of a different name, as is the case with the unary operator methods, be delegated or forwarded to another object via an alternative name, or treated any which way by method_missing. We can make this matter tractable through division: objects receive messages; objects invoke methods. This distinction is also useful when considering #respond_to? and #respond_to_missing?: if a message expression is just the invoking of a named method, how do we explain #method_defined?, the #respond_to\* pair, or #send? That's an overview, at least.

I chose to standardise on Unicode character names because there are multiple legitimate terms for most ASCII punctuation. This is underscored, pun unintentional, by the recent silliness around terming '{' a moustache. Then you have '#', which is called variously a 'number sign', 'pound sign' (further confusing it with '£'), 'hash mark', an 'octothorpe', and a 'sharp'. Your example of 'full stop' is interesting because that is the common term for '.' in English; 'period' and the like are Americanisms. Terms like 'dash' made some sense in the context of ASCII, but there are nearly fifty Unicode characters with 'dash' in their names. So, while I find some of Unicode's naming choices peculiar, I recognise the need for standardisation, and I can think of no better body to concede to.  

However, omitting the characters themselves from the headings was indeed an oversight which I have corrected. (Originally, they appeared in a large typeface in the left margin, but I can't recall what happened to that). I've added the alternative terms you suggest to the text, also.

**Comment by coatl** [comment]
I always prefer the common terminology in actual use as opposed to more academic, theoretically correct wordings. However, I am trying to resist my usual urge to argue every little point. You inclusion of the alternate character names and actual glyphs goes a great way to making this section clearer, thank you. So, I now pronounce myself satisfied.

**Comment by runpaint** [comment]
:-) I've opened another ticket (#33) for the "message expression" terminology. I need to think about that some more.
