### ISSUE TITLE
Replace Pygments

### ISSUE THREAD

**Issue by runpaint** [runpaint/read-ruby#40]
Use a different syntax highlighter. Preferably, pure Ruby and based upon Ripper.

**Comment by rubychan** [comment]
There are basically three non-Pygments choices for syntax highlighting in the Ruby world (to my knowledge): Syntax, CodeRay, and Ultraviolet.

Syntax is outdated, buggy, and no longer maintained.
Ultraviolet is using TextMate's bundles, and supports Ruby quite well. I'm not sure it runs on 1.9 though, because it uses the Oniguruma Gem. It gives me errors when I try to install it.

CodeRay is my library. It is pure Ruby, but not based on Ripper, partly because it targets Ruby 1.8, and partly because it has to cope with broken code. I'm not sure it's a good idea to base a highlighter on a strict parser.

Whatever, you can test CodeRay here:

  http://coderay.rubychan.de/rays

I think the highlighter is really good at Ruby, and it also supports some Ruby 1.9 syntax. If anything is missing, Read Ruby would be the perfect motivation for me to improve it.

I'm not really into Git, but I think this is the point where you expect me to fork something? ;-)

**Comment by runpaint** [comment]
> I think the highlighter is really good at Ruby, and it also supports some Ruby 1.9 syntax. If > anything is missing, Read Ruby would be the perfect motivation for me to improve it.

That sounds wonderful. I'll use CodeRay, then.

> I'm not really into Git, but I think this is the point where you expect me to fork 
> something? ;-)

:-) I'm currently putting the finishing touches to a rewrite of the book using Docbook. That will change the build process somewhat, so I'll switch highlighters at that point. 

Thanks for your help.

**Comment by rubychan** [comment]
> That sounds wonderful. I'll use CodeRay, then.

Great!

A warning: The latest 0.9 release is stable, but has problems with non-ASCII characters. The 1.0 trunk is very unstable currently. I'm working on an improved release (0.9.5) with UTF-8 support.

**Comment by runpaint** [comment]
CodeRay is now used as of df3378fa142fff557e52
